### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by antulik** [lbarasti/ytry#1]
That's an interesting gem and I have a question about API you've chosen.

This gem simplifies code but also adds additional complexity of new methods `map`, `select`, `recover` etc. The first two names conflict with Enum methods in my opinion which confuses users, as they are mostly used for collections. My point - there is no way to understand the code without reading the gem's documentation.

``` ruby
Try { File.read(json_file) }
    .map {|content| JSON.parse(content)}
    .select {|table| table.is_a? Array}
    .recover {|e| puts "Recovering from #{e.message}"; []}
```

What I thought why not to use a well know and accepted Promise interface used in Javascript. For example the same code could be written as

``` ruby
Try { File.read(json_file) }
    .then {|content| JSON.parse(content)}
    .then {|table| table.is_a?(Array) or raise 'Not array' }
    .catch {|e| puts "Recovering from #{e.message}"; []}
```

Thoughts?

**Comment by lbarasti** [comment]
Hey @antulik, thanks for your comment.

> [...] methods map, select, recover etc. The first two names conflict with Enum methods...

That is exactly what we are going for here. In fact, the Try module _includes_ Enumerable.

Even more, Try instances are array-like object - you can think of them as collections containing either one element or none.

From that perspective it makes sense to `map` and `select` on a Try in the same way you `map` and `select` on an Array.

In fact, on a more theoretical note, even though `#map` is often associated to collections, it's meaning is not bound to collections at all. `#map` is about [_mapping_ a function into an other function](https://en.wikipedia.org/wiki/Map_%28higher-order_function%29).
In our context, one way of reading

```
Try{ rand(10) }.map{|v| v.to_s(2)}
```

is that `#map` takes a block that turns a Number into a String, and turns it into a function that takes a Try of a Number and returns a Try of a String. The resulting function is then called on `Try{rand(10)}`

For what concerns the promise-like methods naming, I have a few considerations.
- I've always seen `then` used in the context of asynchronous operations. Try blocks run synchronously, and calling `then` on them might be misleading.
- the beauty of `#select` is that you don't need to explicitly raise an Error when the block returns false. If all is well a Failure with message "Element not found" will be returned in such cases.
- as for `catch`, [Ruby's catch](http://ruby-doc.org/core-2.3.1/Kernel.html#method-i-catch) is something a bit different than one might expect. It looks a lot like a `goto`, or, as it's pointed out [here](http://phrogz.net/programmingruby/tut_exceptions.html) it might be useful when you need "to jump out of some deeply nested construct during normal processing"

That said I think your argument is very valid, and I can definitely see the point of aliasing `recover` to `rescue`, to better comply with Ruby's error handling naming. I'm a bit warier of aliasing `map` with `then`, but if the community wants so, then that's something we can change.

**Comment by antulik** [comment]
@lbarasti right, that makes more sense now. What's the main reason for choosing Enumerable interface? As far as I can see the same functionality could be achieved without it. Is it only for syntax matching (map,select) or something else?

I'm with you on `catch` just tried to simplify example with JS comparison. I would prefer `rescue`.

**Comment by lbarasti** [comment]
Sure, the decision of including Enumerable is mainly practical - we get quite a few useful methods _almost_ for free. I'm mainly thinking about `map`, `select`, `reduce` and `grep`, but also `any?` and `include?`. But you are right, the same functionality could be achieved without it.

BTW, I'm not totally sold on including Enumerable myself as it clutters the Try module with methods that don't make much sense for a Try - like `chunk` or `drop_while`. On the other hand the inclusion makes dealing with a Try almost the same as dealing with an Array (is that a good thing? I don't know yet). Again, the main reason for the inclusion so far is the idea that we have less code to maintain.

Finally, I plan to include `Try#rescue` in the next release ;) Thanks!

**Comment by antulik** [comment]
there is little value in having `map, select, reduce, grep, any?` because as you've said "collections containing either one element or none". Yes you get a lot of free, but you don't want most of it anyway.

From maintenance perspective sure, it totally make sense to have clear code and delegate functionality to other library.

From user perspective clear syntax is everything what matters, even if it's a pain to implement and maintain.

Anyway, thanks for the interesting discussion. I've got your perspective which I didn't see before.
